- name: Create a MBR partition table and one partition
  parted:
    device: "{{ (partitioning_root_device_node | split_partition_number)[0] }}"
    state: present
    label: msdos
    number: "{{ (partitioning_root_device_node | split_partition_number)[1] }}"
    flags:
      - boot

- name: Format the partition
  filesystem:
    dev:  "{{ partitioning_root_device_node }}"
    fstype: ext4
    opts: -O ^64bit

- name: Mount the root partition
  mount:
    state: mounted
    src: "{{ partitioning_root_device_node }}"
    path: "{{ partitioning_root_mount_point }}"
    fstype: ext4
    opts: rw,relatime

- name: Export variables
  set_fact:
    partitioning_root_mount_point:      "{{ partitioning_root_mount_point }}"
    partitioning_root_device_node:      "{{ partitioning_root_device_node }}"
