  - name: Start VirtualBox service
    systemd:
      name: vboxservice
      state: started
      enabled: yes

  - name: Enable QEMU guest agent
    systemd:
      name: qemu-guest-agent
      state: started
      enabled: yes
