# All user information pertaining to root. For the moment there's just the
# password.
users_root_info:
    password: "abcd$1234_root"

# User info for all non-root users.
#
# The dictionary name (i.e. manu) is used as the user name.
#
# Users with `is_admin` set to true will be able to call sudo to perform any
# task as root, with their password asked.
#
# Additional groups can be added via the `groups` list. To make a user
# sudo-enabled, set `is_admin` to true, _do not_ add `wheel` to `groups`.
users_info:
  manu:
    password: "abcd$1234_manu"
    is_admin: true # Optional item, true if missing
    groups: []     # Optional item, empty list if missing

# Increase or decrease the number of rounds used to generate password hashes
users_hash_rounds: 500000

# Set to true to override the system-wide password hashing policy to match what
# is used for the initial user passwords. As of now, Arch already uses SHA512,
# so this only adds rounds, but this may change in future system installations.
# Please note that due to the format of PAM files, it may be difficult to strip
# parameters related to the old algorithm, so it is recommended to check
# /etc/pam.d/passwd for saneness if setting this to true.
users_override_passwd_hash_systemwide: no
