- name: Gather the API for the partitioning flow
  include_role:
    name: "{{ disksetup_roles_prefix }}api"
  vars:
    namespace: partitioning_api

- name: Check API version
  assert:
    that: partitioning_api.apiVersion in disksetup_supported_apis
    fail_msg: >-
        Sorry, but this version of arch-ansible only supports the following
        API versions: {{ disksetup_supported_apis | join(", ") }}

# Actually we only support v1, so assume it

- include_role:
    public: yes
    name: "{{ disksetup_roles_prefix }}partitioning"
- import_role:
    name: base_packages
- include_role:
    public: yes
    name: "{{ disksetup_roles_prefix }}postpartitioning"
- include_role:
    public: yes
    name: "{{ disksetup_roles_prefix }}bootloader"
