- name: Install KVM additions
  pacman:
    name:
      - spice-vdagent
      - qemu-guest-agent
  notify: Enable QEMU guest agent
  register: _self
  changed_when: _self.changed or (run_handlers | default(false))

- include_tasks: ./mplugd.yaml
  when: virtguest_use_mplugd
