- name: Should we use a partitioning flow
  set_fact:
    partitioning_use_flow: yes
  tags: partitioning

- name: Invoke partitioning method
  include_tasks: >-
    {%- if partitioning_use_flow | default(false) -%}
        flow.yaml
    {%- else -%}
        manual.yaml
    {%- endif -%}
