- name: Generate fstab
  vars:
    fstab: "{{ chroot | quote }}/etc/fstab"
  shell: |
    set -e
    set -o pipefail
    {
      if [ -f {{ fstab }} ]; then cat {{ fstab }}; fi
      genfstab -U {{ chroot | quote }} > {{ fstab }}
      cat {{ fstab }}
    } | sort | uniq -u
  register: _fstab_created
  changed_when: _fstab_created.stdout
