- name: Install GRUB2 package
  import_role:
    name: pacstrap
  vars:
    chroot: "{{ partitioning_root_mount_point }}"
    packages:
      - grub
      - grub-btrfs

- name: Install GRUB2
  command: arch-chroot {{ partitioning_root_mount_point | quote }} /usr/bin/grub-install {{ partitioning_priv_device_node | quote }}

- name: Generate GRUB2 configuration file
  command: arch-chroot {{ partitioning_root_mount_point | quote }} /usr/bin/grub-mkconfig -o /boot/grub/grub.cfg

- name: Enable grub-btrfs
  command: systemctl --root={{ partitioning_root_mount_point | quote }} enable grub-btrfs.path
