##### Public variables used by the rest of the playbook #####
partitioning_root_mount_point: "/mnt"

##### Private variables used only by the partitioning roles #####

# On this device node, two partitions will be created:
# * /dev/xxx1 will be used as /boot
# * /dev/xxx2 will be used as a PV to host /
partitioning_priv_device_node: "/dev/sda"

# The boot partition will be this large, in bytes (plus any alignment
# constraint)
partitioning_priv_boot_size: "{{ 512 * 1024 * 1024 }}"

# Names for the VG and LV
partitioning_priv_vg_name: "arch"
partitioning_priv_lv_name: "root"
