- name: Create the EFI partition
  parted:
    device: "{{ partitioning_priv_device_node }}"
    state: present
    label: gpt
    number: 1
    name: ESP
    part_start: "{{ 1024 * 1024 }}B"
    part_end: "{{ partitioning_priv_esp_size | int  + 1024 * 1024 - 1 }}B"
    flags:
      - esp

- name: Create the root partition
  parted:
    device: "{{ partitioning_priv_device_node }}"
    state: present
    label: gpt
    number: 2
    name: root
    part_start: "{{ partitioning_priv_esp_size | int  + 1024 * 1024 }}B"

- name: Enumerate created partitions
  shell: lsblk -n -o PATH {{ partitioning_priv_device_node | quote }} | tail -n +2
  register: _partitions
  changed_when: no

- name: Assign partitions to variables
  set_fact:
    partitioning_priv_esp_device_node: "{{ _partitions.stdout_lines[0] }}"
    partitioning_priv_root_device_node: "{{ _partitions.stdout_lines[1] }}"

- name: Format the ESP
  filesystem:
    dev:  "{{ partitioning_priv_esp_device_node }}"
    fstype: vfat

- name: Format the root partition
  filesystem:
    dev:  "{{ partitioning_priv_root_device_node }}"
    fstype: ext4

- name: Mount the root partition
  mount:
    state: mounted
    src: "{{ partitioning_priv_root_device_node }}"
    path: "{{ partitioning_root_mount_point }}"
    fstype: ext4

- name: Create /boot/efi mountpoint
  file:
    state: directory
    name: "{{ partitioning_root_mount_point }}/boot/efi"
    recurse: yes

- name: Mount the ESP
  mount:
    state: mounted
    src: "{{ partitioning_priv_esp_device_node }}"
    path: "{{ partitioning_root_mount_point }}/boot/efi"
    fstype: vfat
