- name: Install the base system
  hosts: all
  tags:
    - bootstrap
    - never
  environment: "{{ global_proxy_env }}"
  tasks:
    - include_role:
        name: custom_repos
    - import_role:
        name: partitioning
      tags: partitioning
    - include_role:
        name: configure
  post_tasks:
   - name: Reboot into the system
     tags: reboot
     reboot:

- name: Configure the installed system
  hosts: all
  tags: mainconfig
  environment: "{{ global_proxy_env }}"
  roles:
    # The hostname is set once during bootstrap and once here. The idea is to
    # set it as early as possible, but if bootstrap is skipped (i.e.
    # provisioning with Vagrant) we do it again here.
    - role: hostname
    - role: custom_repos
    - role: users
    - role: locale
    - role: proxy
    - role: virtguest
      when: virtguest_enabled | default(True)
    - role: xfce_user_customizations
      when: xfce_user_customizations_enabled | default(True)
    - role: yay_user_customizations
      when: yay_user_customizations_enabled | default(True)
    - role: ttf_fonts
      when: ttf_fonts_enabled | default(True)
    - role: utils
      when: utils_enabled | default(True)
    - role: xutils
      when: xutils_enabled | default(True)
    - role: bluetooth
      when: bluetooth_enabled | default(True)
  tasks:
    - name: Call custom roles
      include_role:
        name: "{{ custom_roles_entry_point }}"
      when: custom_roles_entry_point | default("") != ""

- name: Clean and reboot
  hosts: all
  tags: mainconfig
  environment: "{{ global_proxy_env }}"
  roles:
    - role: clean
  post_tasks:
    - reboot:
      tags: reboot
